CREATE TABLE dbo.PaymentItems
(
	Id INT IDENTITY(1,1) NOT NULL CONSTRAINT PK_PaymentItems PRIMARY KEY,
	PaymentId INT NOT NULL CONSTRAINT FK_PaymentItems_PaymentId FOREIGN KEY REFERENCES dbo.Payments(Id),
	Name NVARCHAR(255) NOT NULL,
	Quantity INT NOT NULL,
	Price DECIMAL(9,2) NOT NULL
)
