CREATE TABLE dbo.Payments
(
	Id INT IDENTITY(1, 1) NOT NULL CONSTRAINT PK_Payments PRIMARY KEY,
	PublicId UNIQUEIDENTIFIER NOT NULL CONSTRAINT DF_Payments_APIKey DEFAULT NEWID(),
	StoreId INT NOT NULL CONSTRAINT FK_Payments_StoreId FOREIGN KEY REFERENCES dbo.Stores(Id),
	Provider VARCHAR(255) NOT NULL,
	Custom NVARCHAR(255) NULL,
	Amount DECIMAL(9,2) NOT NULL,
	Currency CHAR(3) NOT NULL,
	Receiver NVARCHAR(255) NULL,
	JsonData NVARCHAR(MAX) NULL,
	IsCompleted BIT NOT NULL CONSTRAINT DF_Payments_IsCompleted DEFAULT 0,
	CompletedDate DATETIME2(0) NULL,
	IsNotified BIT NOT NULL CONSTRAINT DF_Payments_IsNotified DEFAULT 0,
	NotifiedDate DATETIME2(0) NULL,
	NotifiedCount TINYINT NOT NULL CONSTRAINT DF_Payments_NotifiedCount DEFAULT 0,
	CreateDate DATETIME2(0) NOT NULL CONSTRAINT DF_Payments_CreateDate DEFAULT SYSDATETIME(),
	CONSTRAINT UK_Payments UNIQUE (PublicId)
)
