CREATE TABLE dbo.Stores
(
	Id INT IDENTITY(1, 1) NOT NULL CONSTRAINT PK_Stores PRIMARY KEY,
	APIKey UNIQUEIDENTIFIER NOT NULL CONSTRAINT DF_Stores_APIKey DEFAULT NEWID(),
	Name NVARCHAR(255) NOT NULL,
	LogoUrl NVARCHAR(255) NOT NULL,
	BackgroundUrl NVARCHAR(255) NULL,
	DefaultCurrency CHAR(3) NOT NULL,
	DefaultNotifyUrl NVARCHAR(255) NOT NULL,
	DefaultCancelUrl NVARCHAR(255) NOT NULL,
	DefaultReturnUrl NVARCHAR(255) NOT NULL,
	IsPublic BIT NOT NULL CONSTRAINT DF_Stores_IsPublic DEFAULT 0,
	UpdateDate DATETIME2(0) NOT NULL CONSTRAINT DF_Stores_UpdateDate DEFAULT SYSDATETIME(),
	CreateDate DATETIME2(0) NOT NULL CONSTRAINT DF_Stores_CreateDate DEFAULT SYSDATETIME(),
	CONSTRAINT UK_Stores UNIQUE (APIKey)
)
