CREATE TABLE dbo.Users
(
	Id INT IDENTITY(1,1) NOT NULL CONSTRAINT PK_Users PRIMARY KEY,
	Name VARCHAR(255) NOT NULL CONSTRAINT UK_Users UNIQUE,
	FirstName NVARCHAR(255) NOT NULL,
	LastName NVARCHAR(255) NOT NULL,
	PasswordHash VARBINARY(128) NULL,
	CreateDate DATETIME2(0) NOT NULL CONSTRAINT DF_Users_CreateDate DEFAULT SYSDATETIME()
)
