CREATE TABLE [dbo].[QRTZ_SIMPLE_TRIGGERS] (
    [SCHED_NAME]      NVARCHAR (120) NOT NULL,
    [TRIGGER_NAME]    NVARCHAR (150) NOT NULL,
    [TRIGGER_GROUP]   NVARCHAR (150) NOT NULL,
    [REPEAT_COUNT]    INT            NOT NULL,
    [REPEAT_INTERVAL] BIGINT         NOT NULL,
    [TIMES_TRIGGERED] INT            NOT NULL,
    CONSTRAINT [PK_QRTZ_SIMPLE_TRIGGERS] PRIMARY KEY CLUSTERED ([SCHED_NAME] ASC, [TRIGGER_NAME] ASC, [TRIGGER_GROUP] ASC),
    CONSTRAINT [FK_QRTZ_SIMPLE_TRIGGERS_QRTZ_TRIGGERS] FOREIGN KEY ([SCHED_NAME], [TRIGGER_NAME], [TRIGGER_GROUP]) REFERENCES [dbo].[QRTZ_TRIGGERS] ([SCHED_NAME], [TRIGGER_NAME], [TRIGGER_GROUP]) ON DELETE CASCADE
);

