CREATE TABLE [dbo].[QRTZ_SCHEDULER_STATE] (
    [SCHED_NAME]        NVARCHAR (120) NOT NULL,
    [INSTANCE_NAME]     NVARCHAR (200) NOT NULL,
    [LAST_CHECKIN_TIME] BIGINT         NOT NULL,
    [CHECKIN_INTERVAL]  BIGINT         NOT NULL,
    CONSTRAINT [PK_QRTZ_SCHEDULER_STATE] PRIMARY KEY CLUSTERED ([SCHED_NAME] ASC, [INSTANCE_NAME] ASC)
);

