CREATE TABLE [dbo].[QRTZ_JOB_DETAILS] (
    [SCHED_NAME]        NVARCHAR (120)  NOT NULL,
    [JOB_NAME]          NVARCHAR (150)  NOT NULL,
    [JOB_GROUP]         NVARCHAR (150)  NOT NULL,
    [DESCRIPTION]       NVARCHAR (250)  NULL,
    [JOB_CLASS_NAME]    NVARCHAR (250)  NOT NULL,
    [IS_DURABLE]        BIT             NOT NULL,
    [IS_NONCONCURRENT]  BIT             NOT NULL,
    [IS_UPDATE_DATA]    BIT             NOT NULL,
    [REQUESTS_RECOVERY] BIT             NOT NULL,
    [JOB_DATA]          VARBINARY (MAX) NULL,
    CONSTRAINT [PK_QRTZ_JOB_DETAILS] PRIMARY KEY CLUSTERED ([SCHED_NAME] ASC, [JOB_NAME] ASC, [JOB_GROUP] ASC)
);

